### PR TITLE
Fix improper string handling which caused crashes

### PR DESCRIPTION
**Pull request by jeramey**
parseCloudData() made the assumption that other cloud phenomena parts
of the token would always be 3 characters or less. It was mistaken.

A real-world METAR report violated this assumption in the 01Z cycle on
February 10, 2020. It has been added to the test suite.

This change ensures that only up to 3 chars will be put into the
.other_cld_phenom buffer.

### CODE REVIEW

**Comment by lehenbauer** [comment]
I see.  So there was a space missing between "SCT040" and "22/17", which would have been a temperature and dewpoint, and the three-character limitation would have resulted in a properly recorded scattered clouds at 4,000 AGL.

**Comment by bovine** [comment]
null termination of the destination string might be an issue with strncpy if the token is that long.

**Comment by jeramey** [comment]
Destination string--`.other_cld_phenom` struct member--is currently defined as 4 bytes long and is initialized with '\0' bytes, so null termination isn't an issue with this change.

It may not be worth writing the code to try to figure out if two METAR tokens were accidentally concatenated together since this was almost certainly introduced by simple human error and is likely fairly rare.

**Review by bovine — APPROVED** [review]
ok sounds reasonable

**Pull request merged**
